name: dockbench
channels:
- pytorch
- defaults
- acellera
dependencies:
- moleculekit=0.1.6
- rdkit=2017.09.2.0
- ipython=7.3.0
- matplotlib=2.2.2
- numpy=1.15.4
- pandas=0.24.1
- pip=19.0.3
- python=3.6.6
- scikit-learn=0.20.2
- scipy=1.2.1
- sqlite=3.26.0
- tqdm=4.31.1
- pytorch=1.0.1
- torchvision=0.2.1
- openbabel=2.4.1
- htmd-pdb2pqr=2.1.1
