name: dockbench
channels:
- pytorch
- defaults
- acellera
dependencies:
- moleculekit
- rdkit=2017.09.2.0
- ipython=7.3.0
- matplotlib
- seaborn
- numpy
- pandas
- pip
- python=3.6.6
- scikit-learn
- scipy
- tqdm
- pytorch=1.0.1
- torchvision=0.2.1
- openbabel
- htmd-pdb2pqr
